---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m
  selector:
    matchLabels:
      app: mc-app
  template:
    metadata:
      labels:
        app: mc-app
    spec:
      containers:
      - name: mc-app
        image: narra18/niteeshyncicd:9
        ports:
        - containerPort: 8080

  

